### ISSUE TITLE
Elapsed time not formatted correctly

### ISSUE THREAD

**Issue by kcam01** [adamoutler/anycubic-python#2]
Elapsed time not formatted correctly. The hour is in the minutes section
![image](https://user-images.githubusercontent.com/17442074/159153345-9de5f28e-118b-4616-9e0b-f2a5de798b50.png)

**Comment by adamoutler** [comment]
This is really odd because the same decoder is used to convert both times.  In order to troubleshoot, I'm going to need to add log messages in a hour or two.  I'll reach out over alternative channels when possible.  I'm going to want to capture several of them, at least  30, from the terminal:`ha core log`. And a screenshot from the printer.  I will process, and determine the issue.   I need help with this because I'm waiting for support. 
![Screenshot_20220320-090720](https://user-images.githubusercontent.com/527919/159163807-29340fd0-5d51-4a2c-ba59-bf0ef8cc08cd.png)

**Comment by adamoutler** [comment]
Please perform the following procedure.

1. Adjust the IP address.
2. Open SSH/Terminal program in Home Assistant.
3. Copy and paste all of this into your terminal. 
4. Let it run for 30 minutes then press ctrl-c to terminate.
5. Send me the contents of /share/debug.txt. 

Note: The contents will contain your WiFi Network SSID and device serial number. If you are comfortable, attach the file here.  Otherwise you may use [https://hackedyour.info](https://hackedyour.info) to paste the contents, then send them to me via PM on Reddit. 

Script:
```
printerIp=192.168.1.254
cd /share
pip install uart-wifi==0.0.5.1
monox.py --ipaddress=${printerIp} --command=sysinfo --raw|tee -a debug.txt
monox.py --ipaddress=${printerIp} --command=getfile --raw|tee -a debug.txt
while true; do
   monox.py --ipaddress=${printerIp} --raw|tee -a debug.txt
   sleep 5
done;
```

Should look like this  
![image](https://user-images.githubusercontent.com/527919/159169197-3c704e44-7d09-476a-b75f-a1ebd19deede.png)

**Comment by kcam01** [comment]
attached
[debug.txt](https://github.com/adamoutler/anycubic-python/files/8311934/debug.txt)

**Comment by adamoutler** [comment]
Thanks, what's the total duration of this print and how long was it running when you started?

**Comment by kcam01** [comment]
It was about 3.34 hours. started about 10mins in.

**Comment by kcam01** [comment]
[debug.txt](https://github.com/adamoutler/anycubic-python/files/8312375/debug.txt)

**Comment by adamoutler** [comment]
Thanks.  Pushed an update which should address this issue.

**Comment by adamoutler** [comment]
Fixed?
